apiVersion: skaffold/v3
kind: Config
metadata:
  name: rain-cloud

build:
  local:
    concurrency: 0
    push: true
    useBuildkit: true
  artifacts:
  - image: app-files
    ko:
      flags:
        - -tags=files
      main: ./pkg/cmd/app
  - image: app-provisioning_api
    ko:
      flags:
        - -tags=provisioning_api
      main: ./pkg/cmd/app
  - image: app-theming
    ko:
      flags:
        - -tags=theming
      main: ./pkg/cmd/app
  - image: app-user_status
    ko:
      flags:
        - -tags=user_status
      main: ./pkg/cmd/app
  - image: app-core
    ko:
      flags:
        - -tags=core
      main: ./pkg/cmd/app
  - image: frontend
    context: nextcloud/neon
    docker:
      dockerfile: nextcloud/neon/packages/app/Dockerfile

deploy:
  kubeContext: k3d-rain-cloud-local
  helm:
    releases:
      - name: rain-cloud
        chartPath: helm/rain-cloud
        namespace: rain-cloud
        createNamespace: true
        setValueTemplates:
          apps.files.image: app-files
          apps.provisioning_api.image: app-provisioning_api
          apps.theming.image: app-theming
          apps.user_status.image: app-user_status
          apps.core.image: app-core
          frontend.image: frontend
