apiVersion: skaffold/v3
kind: Config
metadata:
  name: rain-cloud

build:
  local:
    concurrency: 0
    push: true
  artifacts:
  - image: app-provisioning_api
    ko:
      flags:
        - -tags=provisioning_api
  - image: app-theming
    ko:
      flags:
        - -tags=theming
  - image: app-core
    ko:
      flags:
        - -tags=core

deploy:
  kubeContext: k3d-rain-cloud-local
  helm:
    releases:
      - name: rain-cloud
        chartPath: helm/rain-cloud
        namespace: rain-cloud
        createNamespace: true
        setValueTemplates:
          apps.provisioning_api.image: app-provisioning_api
          apps.theming.image: app-theming
          apps.core.image: app-core
