apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rain-cloud.fullname" . }}-app-provisioning-api
  labels:
    {{- include "rain-cloud.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: app-provisioning_api
      {{- include "rain-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: app-provisioning_api
        {{- include "rain-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app-provisioning-api
          image: "{{ .Values.apps.provisioning_api.image }}"
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: app-provisioning-api
spec:
  selector:
    app: app-provisioning_api
  ports:
    - port: 8000
      targetPort: 8000
