apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rain-cloud.fullname" . }}-controller
  labels:
    {{- include "rain-cloud.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: controller
      {{- include "rain-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: controller
        {{- include "rain-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: controller
          image: "{{ .Values.controller.image }}"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  selector:
    app: controller
  ports:
    - port: 8080
      targetPort: 8080
