apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rain-cloud.fullname" . }}-core
  labels:
    {{- include "rain-cloud.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: core
      {{- include "rain-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: core
        {{- include "rain-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: core
          image: "{{ .Values.core.image }}"
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  selector:
    app: core
  ports:
    - port: 8000
      targetPort: 8000
