apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rain-cloud.fullname" . }}-frontend
  labels:
    {{- include "rain-cloud.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: frontend
      {{- include "rain-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: frontend
        {{- include "rain-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
