apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rain-cloud-backend
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core
                port:
                  number: 8000
