apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rain-cloud.fullname" . }}-backend
  labels:
     {{- include "rain-cloud.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core
                port:
                  number: 8000
