apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rain-cloud.fullname" . }}-backend
  labels:
     {{- include "rain-cloud.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /ocs/v2.php/apps/provisioning_api
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8080
          - path: /ocs/v2.php/cloud/apps
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8080
          - path: /ocs/v2.php/cloud/groups
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8080
          - path: /ocs/v2.php/cloud/user
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8080
          - path: /ocs/v2.php/cloud/users
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8080
          - path: /apps/theming
            pathType: Prefix
            backend:
              service:
                name: app-theming
                port:
                  number: 8080
          - path: /index.php/apps/theming
            pathType: Prefix
            backend:
              service:
                name: app-theming
                port:
                  number: 8080
          - path: /ocs/v2.php/apps/theming
            pathType: Prefix
            backend:
              service:
                name: app-theming
                port:
                  number: 8080
          - path: /avatar
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /index.php/avatar
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /core
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /index.php/core
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /index.php/login
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /ocs/v2.php/cloud
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /ocs/v2.php/collaboration
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /ocs/v2.php/core
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /ocs/v2.php/hovercard
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /ocs/v2.php/profile
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /ocs/v2.php/references
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /ocs/v2.php/search
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /ocs/v2.php/translation
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /status.php
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
