apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rain-cloud.fullname" . }}-backend
  labels:
     {{- include "rain-cloud.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /ocs/v2.php/apps/provisioning_api
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8000
          - path: /ocs/v2.php/cloud/apps
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8000
          - path: /ocs/v2.php/cloud/groups
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8000
          - path: /ocs/v2.php/cloud/user
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8000
          - path: /ocs/v2.php/cloud/users
            pathType: Prefix
            backend:
              service:
                name: app-provisioning-api
                port:
                  number: 8000
          - path: /apps/theming
            pathType: Prefix
            backend:
              service:
                name: app-theming
                port:
                  number: 8000
          - path: /index.php/apps/theming
            pathType: Prefix
            backend:
              service:
                name: app-theming
                port:
                  number: 8000
          - path: /ocs/v2.php/apps/theming
            pathType: Prefix
            backend:
              service:
                name: app-theming
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-core
                port:
                  number: 8000
